### ISSUE TITLE
Gutenberg: Extra Refresh to Push Content In Gutenberg

### ISSUE THREAD

**Issue by dkotter** [10up/distributor#141]
By default, we only allow published content to be Distributed. In the Classic Editor, when you publish an item, the page refreshes and then the admin menu item is added by Distributor, which then allows us to push that item to other connections.

In Gutenberg, there are no page refreshes, so if you publish an item, the item is published but the page doesn't refresh, so the custom menu item is never added. This means you have to manually refresh the page before you can push that item anywhere. Not a huge deal but also not the most intuitive approach. Not sure the best way around this but would be nice, if possible, to listen for the post publish event and then add the dropdown menu.

**Comment by helen** [comment]
I think for the new editor we should probably explore using a side panel instead of the admin bar. Generally we probably need to explore other push UI besides/in addition to the admin bar because it's possible to have it off or not have enough space especially on smaller screens.

**Comment by helen** [comment]
This belongs in a more major 1.7-type of milestone, can call it good enough for a point release in #750 but want to get into this and remove a lot of that hover code for the next release.

**Comment by peterwilsoncc** [comment]
@jeffpaul Do you recall why you added the help wanted tag on this? It looks like it's fixed by the merged PRs #750 and #790.

**Comment by dkotter** [comment]
@peterwilsoncc I can't speak to the tag but there is still an issue here. Those referenced PRs definitely make the integration of Distributor and the block editor nicer but the don't fully solve the issue I opened here.

To recap, by default we only allow published items to be distributed so the distribution menu isn't even loaded if an item is in a non-published state. When an item is published in the block editor, because this doesn't refresh the page the menu is never shown.

We do show this now (coming from those referenced PRs), which lets the user know they need to refresh themselves: 
<img width="289" alt="Distributor refresh message" src="https://user-images.githubusercontent.com/916738/174126589-4b213393-3418-46ee-a7ce-fae1bbcfcdc8.png">

But I think there's still opportunity here for improvement, whether we lazy load in the menu after publish, whether we load it in at the beginning and only show it after publish, some other approach?

Also, and I didn't test this but I wonder if we have the same issue in reverse, for an item that is published and then gets put back in draft. I believe the distribution menu is probably still active until the page refreshes, though I'd have to test to see if it allows you to still distribute that item or not.

**Comment by peterwilsoncc** [comment]
Thanks for clarifying Darin. 

For 1.7.0 I think I will keep the existing PRs as the bug fix and aim to remove the refresh in either 2.0.0 or 2.1.0
