### ISSUE TITLE
all content arriving as single classic block, can't publish

### ISSUE THREAD

**Issue by jshwlkr** [10up/distributor#516]
**Describe the bug**
Running three WP 5.3.2 sites (not multisite) locally via [VVV](https://varyingvagrantvagrants.org/), distributing content via pull seems to lump all content into a single classic editor block. The post is then unable to be published. If I edit the original post the content is added to the classic editor block in the distributed post.

**Expected behavior**
Blocks would remain intact in the distributed content and it would be publishable directly.

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 10.13.6
 - Browser and version: Chrome 79.0.3945.130
 - Distributor version: 1.5.0
 - Theme and version: Twenty Twenty 1.1
 - Other installed plugin(s) and version(s):
Query Monitor 3.5.2
Application Passwords 0.1.1

**Comment by jeffpaul** [comment]
@jshwlkr can you confirm whether Gutenberg is active on the site the content is being pulled from and if so whether that version matches the version on the site pulling content?

**Comment by dkotter** [comment]
This might also be related to #512, which there's an open PR for that we will merge in for a 2.0.0 release.

**Comment by jeffpaul** [comment]
@jshwlkr are you able to test the `develop` version of Distributor as we've merged in a potential fix for this issue and would love your help testing to confirm things now work as expected?

**Comment by jshwlkr** [comment]
I can confirm the same version of Gutenberg is active on both sites. I've tried using `develop`, it is still not working as expected. (I don't know if it's pertinent,  but I'm on PHP 7.3.15.)

**Comment by dinhtungdu** [comment]
I want to clarify this a little bit. The issue only happens with pulled posts of external connections.

Look at the code below, we use `\Distributor\Utils\is_using_gutenberg( new \WP_Post( $obj ) )`, this check is always `false` because we haven't add post content yet.

https://github.com/10up/distributor/blob/6bd81f6338c77bcf7d73e61e1fd767022959c30a/includes/classes/ExternalConnections/WordPressExternalConnection.php#L914-L917
